# To enable this custom logging configuration, set KEDRO_LOGGING_CONFIG to the path of this file.
# More information available at https://docs.kedro.org/en/stable/logging/logging.html
version: 1

disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  rich:
    class: kedro.logging.RichHandler
    rich_tracebacks: True

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
    delay: True

loggers:
  kedro:
    level: INFO
  unet.pipelines.label.nodes:
    level: INFO
    handlers: [rich, info_file_handler]
    propagate: no
    qualname: unet.pipelines.label.nodes

  pyspark_viz_spaceflights:
    level: INFO

root:
  handlers: [rich, info_file_handler]
